---
- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Change Nginx file
  template:
    src: vhost.nginx.conf.j2
    dest: "{{ dest_nginx_conf }}"

- name: Restarted nginx
  service:
    name: nginx
    state: restarted
    
- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded

- name: Enable nginx
  service:
    name: nginx
    enabled: yes