# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_privatekey_module.html#examples
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_publickey_module.html#examples
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/ssl/csr
    state: directory
    mode: '0755'

- name: Generate an OpenSSL private key with a different size (2048 bits)
  openssl_privatekey:
    path: /etc/ssl/private/wordpress.key
    size: 2048

- name: Generate an OpenSSL Certificate Signing Request
  become: true
  openssl_csr: 
    path: /etc/ssl/csr/wordpress.csr
    privatekey_path: /etc/ssl/private/wordpress.key
    country_name: BR
    organization_name: Dev
    email_address: teste@teste.com.br
    common_name: localhost

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/certs/wordpress.crt
    privatekey_path: /etc/ssl/certs/wordpress.key
    csr_path: /etc/ssl/csr/wordpress.csr
    provider: selfsigned

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded