---
- name: Install package php 7.4
  apt:
    name: "{{ pack }}"
    state: present
  vars:
    pack:
    - php7.4-zip
    - php-imagick
    - php7.4-curl
    - php7.4-fpm
    - php7.4-mbstring
    - php7.4-cli
    - php7.4-bcmath
    - php7.4-xml
    - php7.4-mysql
    - php7.4-common
    - php7.4-gd
    - php7.4-json