---
- name: Extract and download wordpress
  ansible.builtin.unarchive:
    src: "{{ url_wp }}"
    dest: "{{ dest_wp_file }}"
    remote_src: yes

- name: Create permission wp {{ wp_path }}
  ansible.builtin.file:
    path: "{{ wp_path }}"
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy file wp-config
  copy:
    src: ../files/wp-config.php
    dest: "{{ dest_wp_conf }}"

- name: Copy file php-info
  copy:
    src: ../files/info.php
    dest: "{{ wp_path }}"