---
- name: Install Prometheus
  apt:
    name: prometheus
    update_cache: yes
    state: present

- name: Enable and Restart Prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes 

- name: Enable and Restart Node Exporter
  service:
    name: prometheus-node-exporter
    enabled: yes
    state: restarted

- name: Install Alert Manager
  apt:
    name: prometheus-alertmanager
    update_cache: yes
    state: present

- name: Enable and Start Alert Manager
  service:
    name: prometheus-alertmanager
    enabled: yes
    state: started
    
- name: Enable and Restart Prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes 